apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  labels:
    app.kubernetes.io/instance: service-mesh
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
