apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: prod-tenant-02
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    openshiftRoute:
      enabled: true
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      name: jaeger-prod2
      install:
        storage:
          type: Elasticsearch
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.1
  telemetry:
    type: Istiod
